package com.docker.jocker.model;

import com.google.gson.annotations.SerializedName;

/**
 * FIXME Waiting for https://github.com/swagger-api/swagger-codegen/issues/358 to get this generated by swagger
 *
 * @author <a href="mailto:nicolas.deloof@gmail.com">Nicolas De Loof</a>
 */
public class ContainerSpec extends ContainerConfig {
    
    @SerializedName("HostConfig")
    private HostConfig hostConfig;

    @SerializedName("NetworkingConfig")
    private NetworkingConfig networkingConfig;

    public HostConfig getHostConfig() {
        return hostConfig;
    }

    public void setHostConfig(HostConfig hostConfig) {
        this.hostConfig = hostConfig;
    }

    public ContainerSpec hostConfig(HostConfig hostConfig) {
        this.hostConfig = hostConfig;
        return this;
    }

    public NetworkingConfig getNetworkingConfig() {
        return networkingConfig;
    }

    public void setNetworkingConfig(NetworkingConfig networkingConfig) {
        this.networkingConfig = networkingConfig;
    }

    public ContainerSpec networkingConfig(NetworkingConfig networkingConfig) {
        this.networkingConfig = networkingConfig;
        return this;
    }
}
